CREATE DATABASE IF NOT EXISTS RouteDb;
USE RouteDb;

CREATE TABLE IF NOT EXISTS Admin(
    Adm_Id INT PRIMARY KEY AUTO_INCREMENT,
    Adm_username VARCHAR(20) UNIQUE,
    Adm_passw VARCHAR(25) NOT NULL,
    Adm_role ENUM('Admin','Staff','Driver')
);

CREATE TABLE IF NOT EXISTS Student(
    Std_id INT PRIMARY KEY AUTO_INCREMENT,
    Std_name VARCHAR(30) NOT NULL,
    class VARCHAR(3) NOT NULL,
    Roll_no INT NOT NULL,
    Std_addrs TEXT NOT NULL,
    contact_num VARCHAR(10) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS Driver(
    Drv_id INT PRIMARY KEY AUTO_INCREMENT,
    Drv_name VARCHAR(30) NOT NULL,
    Drv_lic_no VARCHAR(15) UNIQUE NOT NULL,
    contact_num VARCHAR(10) UNIQUE NOT NULL,
    Adm_Id INT,
    FOREIGN KEY (Adm_Id) REFERENCES Admin(Adm_Id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Route(
    Rte_id INT PRIMARY KEY AUTO_INCREMENT,
    Rte_name VARCHAR(20) NOT NULL,
    start_point VARCHAR(30) NOT NULL,
    end_point VARCHAR(30) NOT NULL,
    Total_distance FLOAT NOT NULL,
    Est_time INT NOT NULL
);

CREATE TABLE IF NOT EXISTS Bus(
    Bus_id INT PRIMARY KEY AUTO_INCREMENT,
    Bus_no VARCHAR(10) UNIQUE NOT NULL,
    capacity INT NOT NULL,
    Drv_id INT,
    Rte_id INT,
    FOREIGN KEY (Drv_id) REFERENCES Driver(Drv_id) ON DELETE CASCADE,
    FOREIGN KEY (Rte_id) REFERENCES Route(Rte_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Stop(
    Stp_id INT PRIMARY KEY AUTO_INCREMENT,
    Stp_name VARCHAR(30) NOT NULL,
    latitude DOUBLE NOT NULL,
    longitude DOUBLE NOT NULL,
    Rte_id INT,
    FOREIGN KEY (Rte_id) REFERENCES Route(Rte_id) ON DELETE CASCADE
);
